name: Build firmware
permissions:
  contents: write
on:
  workflow_dispatch:
    inputs:
      rom_link:
        description: "Rom download link:"
        default: "http://bkt-sgp-miui-ota-update-alisgp.oss-ap-southeast-1.aliyuncs.com/V14.0.4.0.TKFIDXM/miui_SWEETIDGlobal_V14.0.4.0.TKFIDXM_379adc91e8_13.0.zip"
        required: true
        type: string
jobs:
  onDispatch:
    name: On Dispatch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4.1.4
      - name: Install deps
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install python3 python3-pip axel curl file
      - name: Install firmware creator
        run: |
          pip install --upgrade pip
          pip3 install xiaomi_flashable_firmware_creator
      - name: Download ROM
        run: axel ${{ github.event.inputs.rom_link }}
      - name: Execute firmware creator
        run: xiaomi_flashable_firmware_creator -F miui*.zip
      - name: Read version
        id: version
        run: |
          body=$(unzip -p fw_sweet*.zip META-INF/com/android/metadata | grep post-build-incremental | cut -c 25-41)
          echo "BODY=${body}" >> $GITHUB_OUTPUT
      - name: Read full meta
        id: changelog
        run: |
          body=$(unzip -p fw_sweet*.zip META-INF/com/android/metadata | cat)
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo "BODY=${body}" >> $GITHUB_OUTPUT
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: fw_sweet*.zip
          tag: ${{ github.run_id }}
          overwrite: true
          release_name: ${{ steps.version.outputs.BODY }}
          body: ${{ steps.changelog.outputs.BODY }}
          file_glob: true

